name: publish

on:
  deployment:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      - 
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - 
        name: Install packages
        run: npm install
      - 
        name: Build
        run: npm run build
      - 
        name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./dist
          cname: www.gitploy.io
      - 
        name: Deploy successfully
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          deployment_id: ${{ github.event.deployment.id }}
          description: Finish to publish successfully.
          state: "success"
          token: "${{ github.token }}"
      - 
        name: Deploy failed
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          deployment_id: ${{ github.event.deployment.id }}
          description: Failed to publish.
          state: "failure"
          token: "${{ github.token }}"